Dont hide output from browsersync command
drud/ddev-browsersync pull request #38
Opened 2023-01-18 19:25 UTC by mmunz

Is there any reason not to show the output from browser-sync?
This makes it more difficult to debug, e.g. see when files are reloaded.

2023-01-18 20:22 UTC, rfay requested changes
IMO what we should do is pipe it to grep to get rid of the confusing output but keep the update notifications. IIRC this was introduced in https://github.com/drud/ddev-browsersync/pull/31 and it was introduced because people were confused by the info given about the port (telling people to hit localhost:3000)

2023-01-18 21:29 UTC, mmunz commented
@rfay i have added a grep command to remove those misleading urls

2023-01-19 00:55 UTC, tyler36 commented
Looks good to me.

2023-01-19 22:53 UTC, rfay commented
Can be tested with `ddev get https://github.com/mmunz/ddev-browsersync/tarball/dont-hide-browsersync-output`

2023-01-19 22:59 UTC, rfay requested changes
It doesn't seem to work as expected, still shows the bogus URLs:

```
$ ddev browsersync
[Browsersync] Proxying: http://localhost
[Browsersync] Access URLs:
 ------------------------------------
    Local: http://localhost:3000
 External: http://d9.example.com:3000
 ------------------------------------
[Browsersync] Watching files...
```

Also, I note that the README still says 
> NOTE: The browsersync'd URL is HTTPS, not HTTP. ddev-router redirects traffic to HTTPS, but browsersync does not know this.

2023-01-20 00:36 UTC, tyler36 commented
@rfay  I'm not seeing that. 

```shell
$ ddev browsersync
Proxying browsersync on https://browsersync-demo.ddev.site:3000
[Browsersync] Proxying: http://localhost
[Browsersync] Watching files...
```

When I remove the `| grep -v "Access URLs\|--------------------\|Local: http\|External: http"`

```shell
$ ddev browsersync
Proxying browsersync on https://browsersync-demo.ddev.site:3000
[Browsersync] Proxying: http://localhost
[Browsersync] Access URLs:
 ------------------------------------------------
    Local: http://localhost:3000
 External: http://browsersync-demo.ddev.site:3000
 ------------------------------------------------
[Browsersync] Watching files...
```

2023-01-20 00:40 UTC, tyler36 commented
My complete `browsersync` file. I added `TESTING` to the first echo to confirm the correct file is used.

```
#!/bin/bash

#ddev-generated
## Description: Run browser-sync in the web container
## Usage: browsersync
## Example: "ddev browsersync"
## ExecRaw: true

echo "Proxying browsersync on ${DDEV_PRIMARY_URL}:3000 TESTING"
browser-sync start -c /var/www/html/.ddev/browser-sync.js | grep -v "Access URLs\|--------------------\|Local: http\|External: http"
```

```shell
ddev browsersync
Proxying browsersync on https://browsersync-demo.ddev.site:3000 TESTING
[Browsersync] Proxying: http://localhost
[Browsersync] Watching files...
```

DDEV: `1.21.4`
OS: Ubuntu

2023-01-20 00:48 UTC, rfay approved these changes
I had an old browsersync global command that didn't have `#ddev-generated` in it, so didn't get overwritten properly on `ddev get`. 

Now I see the expected results:
```
$ ddev browsersync
Proxying browsersync on https://d9.example.com:3000
[Browsersync] Proxying: http://localhost
[Browsersync] Watching files...
[Browsersync] Reloading Browsers...
[Browsersync] File event [change] : web/core/profiles/demo_umami/themes/umami/css/base.css
```

I kind of wonder if this custom command should be installed at the project level, and I'll take a look and see if the `ddev get` warned me that it was skipping it.

2023-01-20 00:49 UTC, rfay commented
It did in fact warn me, but I wasn't looking, like most people wouldn't be.
> NOT overwriting file/directory /Users/rfay/.ddev/commands/web/browsersync. The #ddev-generated signature was not found in the file, so it will not be overwritten. You can just remove the file and use ddev get again if you want it to be replaced: signature was not found in file /Users/rfay/.ddev/commands/web/browsersync

2023-01-20 00:56 UTC, merged

2023-01-20 06:26 UTC, mmunz commented
> I kind of wonder if this custom command should be installed at the project level, and I'll take a look and see if the `ddev get` warned me that it was skipping it.

Also a good point, i was wondering about this too already. The globally installed command shows up in other ddev projects where the browser-sync addon is not installed. But it does not work there of course.

2023-01-20 06:27 UTC, mmunz commented
Thanks for the fast review and merging.

2023-01-20 07:15 UTC, tyler36 commented
> I kind of wonder if this custom command should be installed at the project level, and I'll take a look and see if the ddev get warned me that it was skipping it.

Hope to get around to making a PR to move it to a project-level command.

2023-01-20 07:15 UTC, tyler36 commented
@mmunz Thanks for contributing!